# Remap prefix from Ctrl+b to Ctrl+a (more ergonomic)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload the config file with Prefix + r
bind r source-file ~/.tmux.conf \; display "Configuration reloaded!"

# Start windows and panes at 1 instead of 0
set -g base-index 1

# Passthrough
set -g allow-passthrough on
set -s set-clipboard on

# Change indices from 0
setw -g pane-base-index 1
set-option -g renumber-windows on


# Use VIM style
set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable mouse support for clicking panes, windows, and resizing
set -g mouse on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Cursor position
set -g status-position top

# Plugins

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-yank'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
